### ISSUE TITLE
Issue with downloading project through command

### ISSUE THREAD

**Issue by shreyareddyedulakanti** [Skyscanner/backpack#3619]
Hi,

When I tried to download the project, it downloaded the node and other folders but the backpack folder seems to be missing and it is shown in the errors below
```$ npx create-react-app my-app --scripts-version=@skyscanner/backpack-react-scripts --template @skyscanner/backpack --use-npm

Creating a new React app in D:\my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and @skyscanner/backpack-react-scripts with @skyscanner/cra-template-backpack...


added 1450 packages in 36s

268 packages are looking for funding
  run `npm fund` for details

Initialized a git repository.
Installing Backpack dependencies using npm

npm warn idealTree Removing dependencies.react in favor of devDependencies.react
npm warn idealTree Removing dependencies.react-dom in favor of devDependencies.react-dom
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated bpk-stylesheets@7.2.16: This package has now been merged into @skyscanner/backpack-web. Please upgrade to version 27.0.0+ to continue getting updates and migrate your imports to '@skyscanner/backpack-web/bpk-stylesheets'
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated bpk-mixins@36.2.0: This package has now been merged into @skyscanner/backpack-web. Please upgrade to version 27.0.0+ to continue getting updates and migrate your imports to '@skyscanner/backpack-web/bpk-mixins'
npm warn deprecated bpk-mixins@32.2.0: This package has now been merged into @skyscanner/backpack-web. Please upgrade to version 27.0.0+ to continue getting updates and migrate your imports to '@skyscanner/backpack-web/bpk-mixins'
npm warn deprecated node-sass@7.0.3: Node Sass is no longer supported. Please use `sass` or `sass-embedded` instead.
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'D:\\my-app\\node_modules\\bpk-stylesheets',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\my-app\node_modules\bpk-stylesheets\node_modules\@skyscanner\bpk-svgs'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'D:\\my-app\\node_modules\\bpk-stylesheets\\node_modules\\@skyscanner\\bpk-svgs'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path D:\my-app\node_modules\node-sass
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm error Building: C:\Program Files\nodejs\node.exe D:\my-app\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm error gyp info it worked if it ends with ok
npm error gyp verb cli [
npm error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm error gyp verb cli   'D:\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm error gyp verb cli   'rebuild',
npm error gyp verb cli   '--verbose',
npm error gyp verb cli   '--libsass_ext=',
npm error gyp verb cli   '--libsass_cflags=',
npm error gyp verb cli   '--libsass_ldflags=',
npm error gyp verb cli   '--libsass_library='
npm error gyp verb cli ]
npm error gyp info using node-gyp@8.4.1
npm error gyp info using node@20.16.0 | win32 | x64
npm error gyp verb command rebuild []
npm error gyp verb command clean []
npm error gyp verb clean removing "build" directory
npm error gyp verb command configure []
npm error gyp verb find Python Python is not set from command line or npm configuration
npm error gyp verb find Python Python is not set from environment variable PYTHON
npm error gyp verb find Python checking if "python3" can be used
npm error gyp verb find Python - executing "python3" to get executable path
npm error gyp verb find Python - "python3" is not in PATH or produced an error
npm error gyp verb find Python checking if "python" can be used
npm error gyp verb find Python - executing "python" to get executable path
npm error gyp verb find Python - executable path is "C:\Users\ESHRE\AppData\Local\Programs\Python\Python310\python.exe"
npm error gyp verb find Python - executing "C:\Users\ESHRE\AppData\Local\Programs\Python\Python310\python.exe" to get version
npm error gyp verb find Python - version is "3.10.6"
npm error gyp info find Python using Python version 3.10.6 found at "C:\Users\ESHRE\AppData\Local\Programs\Python\Python310\python.exe"
npm error gyp verb get node dir no --target version specified, falling back to host node version: 20.16.0
npm error gyp verb command install [ '20.16.0' ]
npm error gyp verb install input version string "20.16.0"
npm error gyp verb install installing version: 20.16.0
npm error gyp verb install --ensure was passed, so won't reinstall if already installed
npm error gyp verb install version is already installed, need to check "installVersion"
npm error gyp verb got "installVersion" 9
npm error gyp verb needs "installVersion" 9
npm error gyp verb install version is good
npm error gyp verb get node dir target node version installed: 20.16.0
npm error gyp verb build dir attempting to create "build" dir: D:\my-app\node_modules\node-sass\build
npm error gyp verb build dir "build" dir needed to be created? Yes
npm error gyp verb find VS msvs_version not set from command line or npm config
npm error gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm error gyp verb find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm error gyp verb find VS looking for Visual Studio 2015
npm error gyp verb find VS - not found
npm error gyp verb find VS not looking for VS2013 as it is only supported up to Node.js 8
npm error gyp ERR! find VS
npm error gyp ERR! find VS msvs_version not set from command line or npm config
npm error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm error gyp ERR! find VS looking for Visual Studio 2015
npm error gyp ERR! find VS - not found
npm error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm error gyp ERR! find VS
npm error gyp ERR! find VS **************************************************************
npm error gyp ERR! find VS You need to install the latest version of Visual Studio
npm error gyp ERR! find VS including the "Desktop development with C++" workload.
npm error gyp ERR! find VS For more information consult the documentation at:
npm error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm error gyp ERR! find VS **************************************************************
npm error gyp ERR! find VS
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm error gyp ERR! stack     at VisualStudioFinder.fail (D:\my-app\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm error gyp ERR! stack     at D:\my-app\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\my-app\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm error gyp ERR! stack     at D:\my-app\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm error gyp ERR! stack     at D:\my-app\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm error gyp ERR! stack     at D:\my-app\node_modules\node-gyp\lib\util.js:54:7
npm error gyp ERR! stack     at D:\my-app\node_modules\node-gyp\lib\util.js:33:16
npm error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:430:5)
npm error gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm error gyp ERR! System Windows_NT 10.0.22631
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm error gyp ERR! cwd D:\my-app\node_modules\node-sass
npm error gyp ERR! node -v v20.16.0
npm error gyp ERR! node-gyp -v v8.4.1
npm error gyp ERR! not ok
npm error Build failed with error code: 1
npm error A complete log of this run can be found in: C:\Users\ESHRE\AppData\Local\npm-cache\_logs\2024-09-27T21_37_48_112Z-debug-0.log
`npm install --no-audit --save-dev @skyscanner/backpack-web@^15.1.0 bpk-mixins@^36.1.1 bpk-stylesheets@^7.2.16 react@^17.0.0 react-dom@^17.0.0` failed
```

I am also using npm start to run it and I am getting the error below in the image. Can anyone help here?
![backpack-issue](https://github.com/user-attachments/assets/96122691-b7c0-4ce8-93e1-d3c4b09513d6)

**Comment by shreyareddyedulakanti** [comment]
Ok
I am going to comment on my issue so that if anybody else is facing the same issue it will be helpful.

1. Remove the node_modules folder and reinstall it using the two commands below:
```rm -rf node_modules/
npm install```

2. Use this command `npm install bpk-stylesheets --save` to install backpack stylesheets.
3. Then install sass using the command `npm install sass --save`.
4. Then if you do `npm start` you will still be getting an error like `padding: $bpk-spacing-lg * 2;` undefined variable. This was resolved in another ticket putting that ticket ([stylesheet issue](https://github.com/Skyscanner/backpack/issues/3575)) and also mentioning it here: 
Update this one `padding: $bpk-spacing-lg * 2;` to `padding: bpk-spacing-lg() * 2;`
There will be other errors similar to this one remove $ and add() to the end.

Thanks
